### ISSUE TITLE
VideoTrackRenderer for local has been blacked when toggle video status

### ISSUE THREAD

**Issue by lxl518000** [livekit/client-sdk-flutter#166]
thanks for your sdk !

i found that VideoTrackRenderer for local has been blacked when toggle video status!

the vedio status is enabled when i connected to the room.

and then setCameraEnabled(false) ,looks well;

and then setCameraEnabled(true) , the other members can view my camera video;

but my local VideoTrackRenderer  gave a black container withoth anything;

please check it? 
[](url)

https://user-images.githubusercontent.com/7520801/189082490-15fd5e05-0c28-41f1-96e7-78a6d285fcef.mp4

**Comment by lxl518000** [comment]
@cloudwebrtc please check it ?

**Comment by lxl518000** [comment]
> okay, Seems to be a local video track rendering issue, let me test it on my phone.

also ,  when the black screen appears, the camera will not be released after page closed;

hope this information is useful  ！

**Comment by lxl518000** [comment]
> 好吧，好像是本地视频轨道渲染问题，让我在手机上测试一下。
Hi bro, it's easier to reproduce when there is another person in the room。

**Comment by lxl518000** [comment]
> > 好吧，好像是本地视频轨道渲染问题，让我在手机上测试一下。
> > Hi bro, it's easier to reproduce when there is another person in the room。

this is my test log!

I/org.webrtc.Logging(15920): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging(15920): EglRenderer: EglBase.create shared context
D/HostConnection(15920): HostConnection::get() New Host Connection established 0xd525b230, tid 16880
D/HostConnection(15920): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging(15920): EglBase14Impl: Using OpenGL ES version 2
D/FlutterWebRTCPlugin(15920): CameraEventsHandler.onFirstFrameAvailable
D/eglCodecCommon(15920): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(15920): eglCreateContext: 0xa1855de0: maj 3 min 0 rcv 3
D/EGL_emulation(15920): eglMakeCurrent: 0xa1855de0: ver 3 0 (tinfo 0xd52bff90)
W/FlutterWebRTCPlugin(15920): FlutterRTCVideoRenderer.setVideoTrack, set video track to 30ec23e5-3ea1-46dd-8455-2913ddfd8180
I/org.webrtc.Logging(15920): EglRenderer: Releasing.
I/org.webrtc.Logging(15920): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging(15920): EglRenderer: Releasing done.
I/org.webrtc.Logging(15920): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging(15920): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(15920): EglRenderer: EglBase.create shared context
D/HostConnection(15920): HostConnection::get() New Host Connection established 0xbd0d5250, tid 16881
D/HostConnection(15920): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging(15920): EglBase14Impl: Using OpenGL ES version 2
D/eglCodecCommon(15920): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(15920): eglCreateContext: 0xbd1318e0: maj 3 min 0 rcv 3
D/MediaConstraintsUtils(15920): mandatory constraints are not a map
D/MediaConstraintsUtils(15920): optional constraints are not an array
D/EGL_emulation(15920): eglMakeCurrent: 0xbd1318e0: ver 3 0 (tinfo 0xbd9ef5f0)
I/org.webrtc.Logging(15920): GlShader: Deleting shader.
I/flutter (15920): change
I/flutter (15920): refresh list
I/flutter (15920): [Instance of 'ParticipantTrack']
I/flutter (15920): [{uid: 21, t: 1662632617}, {uid: 13, t: 1662693406}]
I/flutter (15920): change
I/flutter (15920): Instance of 'LocalVideoTrack'
I/flutter (15920): change
I/flutter (15920): refresh list
I/flutter (15920): [Instance of 'ParticipantTrack']
I/flutter (15920): [{uid: 21, t: 1662632617}, {uid: 13, t: 1662693406}]
I/flutter (15920): change
I/flutter (15920): Instance of 'LocalVideoTrack'
I/org.webrtc.Logging(15920): CameraStatistics: Camera fps: 28.
I/org.webrtc.Logging(15920): CameraCapturer: Stop capture
I/org.webrtc.Logging(15920): CameraCapturer: Stop capture: Nulling session
I/org.webrtc.Logging(15920): CameraCapturer: Stop capture done
I/org.webrtc.Logging(15920): CameraCapturer: dispose
I/org.webrtc.Logging(15920): CameraCapturer: Stop capture
I/org.webrtc.Logging(15920): CameraCapturer: Stop capture: No session open
I/org.webrtc.Logging(15920): CameraCapturer: Stop capture done
I/org.webrtc.Logging(15920): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging(15920): Camera2Session: Stop camera2 session on camera 1
I/org.webrtc.Logging(15920): Camera2Session: Stop internal
I/org.webrtc.Logging(15920): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging(15920): Camera2Session: Stop done
I/org.webrtc.Logging(15920): SurfaceTextureHelper: dispose()
I/org.webrtc.Logging(15920): Camera2Session: Camera device closed.
D/FlutterWebRTCPlugin(15920): CameraEventsHandler.onFirstFrameAvailable
I/org.webrtc.Logging(15920): GlShader: Deleting shader.
I/flutter (15920): change
I/flutter (15920): refresh list
I/flutter (15920): change
I/flutter (15920): refresh list
I/flutter (15920): [Instance of 'ParticipantTrack']
I/flutter (15920): [{uid: 21, t: 1662632617}, {uid: 13, t: 1662693406}]
I/flutter (15920): change
I/flutter (15920): Instance of 'LocalVideoTrack'
W/FlutterWebRTCPlugin(15920): FlutterRTCVideoRenderer.setVideoTrack, set video track to null
I/org.webrtc.Logging(15920): EglRenderer: Releasing.
I/org.webrtc.Logging(15920): GlShader: Deleting shader.
I/org.webrtc.Logging(15920): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging(15920): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(15920): EglRenderer: Releasing done.
I/flutter (15920): change
I/flutter (15920): refresh list
I/flutter (15920): [Instance of 'ParticipantTrack']
I/flutter (15920): [{uid: 21, t: 1662632617}, {uid: 13, t: 1662693406}]
I/flutter (15920): change
I/flutter (15920): Instance of 'LocalVideoTrack'
I/flutter (15920): [Instance of 'ParticipantTrack']
I/flutter (15920): [{uid: 21, t: 1662632617}, {uid: 13, t: 1662693406}]
I/flutter (15920): change
I/flutter (15920): Instance of 'LocalVideoTrack'
I/flutter (15920): [Instance of 'ParticipantTrack']
I/flutter (15920): [{uid: 21, t: 1662632617}, {uid: 13, t: 1662693406}]
I/flutter (15920): change
I/flutter (15920): Instance of 'LocalVideoTrack'
I/FlutterWebRTCPlugin(15920): getUserMedia(video): ConstraintsMap{mMap={frameRate=25, facingMode=user, width=960, height=540}}
D/FlutterWebRTCPlugin(15920): Creating video capturer using Camera2 API.
D/FlutterWebRTCPlugin(15920): Create front camera 1 succeeded
D/HostConnection(15920): HostConnection::get() New Host Connection established 0x9fc80000, tid 16887
D/HostConnection(15920): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging(15920): EglBase14Impl: Using OpenGL ES version 2
D/eglCodecCommon(15920): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(15920): eglCreateContext: 0xd52db640: maj 3 min 0 rcv 3
D/EGL_emulation(15920): eglMakeCurrent: 0xd52db640: ver 3 0 (tinfo 0xa6caa3e0)
E/EGL_emulation(15920): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
**E/EGL_emulation(15920): tid 16887: eglQueryContext(1902): error 0x3004 (EGL_BAD_ATTRIBUTE)**
I/org.webrtc.Logging(15920): CameraCapturer: startCapture: 960x540@25
I/org.webrtc.Logging(15920): Camera2Session: Create new camera2 session on camera 1
I/org.webrtc.Logging(15920): Camera2Session: start
D/FlutterWebRTCPlugin(15920): changeCaptureFormat: 960x540@25
D/FlutterWebRTCPlugin(15920): MediaStream id: e57c49b5-eb61-4c74-b652-3d2a53d29979
I/org.webrtc.Logging(15920): Camera2Session: Available preview sizes: [1280x720, 640x480, 320x240, 176x144, 1920x1080]
I/org.webrtc.Logging(15920): Camera2Session: Available fps ranges: [[15.0:30.0], [30.0:30.0]]
I/org.webrtc.Logging(15920): Camera2Session: Using capture format: 640x480@[15.0:30.0]
I/org.webrtc.Logging(15920): Camera2Session: Opening camera 1
D/FlutterWebRTCPlugin(15920): CameraEventsHandler.onCameraOpening: cameraName=1
I/flutter (15920): change
I/flutter (15920): refresh list
I/org.webrtc.Logging(15920): Camera2Session: Camera opened.
I/org.webrtc.Logging(15920): Camera2Session: Camera capture session configured.
I/org.webrtc.Logging(15920): Camera2Session: Stabilization not available.
I/org.webrtc.Logging(15920): Camera2Session: Using continuous video auto-focus.
I/flutter (15920): [Instance of 'ParticipantTrack']
I/flutter (15920): [{uid: 21, t: 1662632617}, {uid: 13, t: 1662693406}]
I/org.webrtc.Logging(15920): Camera2Session: Camera device successfully started.
I/org.webrtc.Logging(15920): CameraCapturer: Create session done. Switch state: IDLE
I/flutter (15920): change
I/org.webrtc.Logging(15920): SurfaceTextureHelper: Setting listener to org.webrtc.-$$Lambda$Camera2Session$CaptureSessionCallback$UDvzHNj8-cAJE1WNByx98pxD9vA@7da9889
I/flutter (15920): Instance of 'LocalVideoTrack'
I/org.webrtc.Logging(15920): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging(15920): EglRenderer: EglBase.create shared context
D/HostConnection(15920): HostConnection::get() New Host Connection established 0xa3f49ca0, tid 16893
D/HostConnection(15920): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging(15920): EglBase14Impl: Using OpenGL ES version 2
D/eglCodecCommon(15920): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(15920): eglCreateContext: 0xbd130980: maj 3 min 0 rcv 3
D/EGL_emulation(15920): eglMakeCurrent: 0xbd130980: ver 3 0 (tinfo 0xa0817260)
W/FlutterWebRTCPlugin(15920): FlutterRTCVideoRenderer.setVideoTrack, set video track to c21d0b6a-3978-4fa5-b8a0-2667e31aa759
I/org.webrtc.Logging(15920): EglRenderer: Releasing.
I/org.webrtc.Logging(15920): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging(15920): EglRenderer: Releasing done.
I/org.webrtc.Logging(15920): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging(15920): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(15920): EglRenderer: EglBase.create shared context
D/HostConnection(15920): HostConnection::get() New Host Connection established 0xa3f49ca0, tid 16894
D/HostConnection(15920): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging(15920): EglBase14Impl: Using OpenGL ES version 2
D/eglCodecCommon(15920): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(15920): eglCreateContext: 0xbd1310a0: maj 3 min 0 rcv 3
D/EGL_emulation(15920): eglMakeCurrent: 0xbd1310a0: ver 3 0 (tinfo 0xa0817230)
I/flutter (15920): change
I/flutter (15920): refresh list
D/FlutterWebRTCPlugin(15920): CameraEventsHandler.onFirstFrameAvailable
I/flutter (15920): [Instance of 'ParticipantTrack']
I/flutter (15920): [{uid: 21, t: 1662632617}, {uid: 13, t: 1662693406}]
I/flutter (15920): change
I/flutter (15920): Instance of 'LocalVideoTrack'
I/.ruyiwallet.ap(15920): NativeAlloc concurrent copying GC freed 38848(2907KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5937KB/11MB, paused 2.455ms total 141.263ms
I/org.webrtc.Logging(15920): CameraStatistics: Camera fps: 28.

**Comment by cloudwebrtc** [comment]
so, this issue is only reproduced on android, will other platforms have it?

**Comment by lxl518000** [comment]
> 所以，这个问题只在android上重现，其他平台会有吗？

Currently I only have the android environment, I use it in combination with the web page ^_^

**Comment by jascodes** [comment]
I have similar issue on flutter web. When somebody disconnects and reconnect.

**Comment by lxl518000** [comment]
hi bro,can there be any progress on this issue?

**Comment by cloudwebrtc** [comment]
Sorry for being busy lately, I will try to close this issue this week, it seems to be related to the video renderer timing.

**Comment by lxl518000** [comment]
> Sorry for being busy lately, I will try to close this issue this week, it seems to be related to the video renderer timing.

hi ，dear cloudwebrtc, It's been a busy week,  wish you  a nice weekend。

please don't forget to check this issue if it's possible .

everything looks fine except for the issue of local camera switching。

sorry for bother again。

**Comment by cloudwebrtc** [comment]
Yes, I have started debugging this issue,

**Comment by cloudwebrtc** [comment]
hey @lxl518000, What version of the example did you use when recording the video?
If yes please try to apply this patch https://github.com/livekit/client-sdk-flutter/commit/82e8a9eedfc3b59932338a5ba93f6cf5934bca0c
I can't seem to recreate this issue in my testing.

**Comment by cloudwebrtc** [comment]
> thanks for your sdk !
> 
> i found that VideoTrackRenderer for local has been blacked when toggle video status!
> 
> the vedio status is enabled when i connected to the room.
> 
> and then setCameraEnabled(false) ,looks well;
> 
> and then setCameraEnabled(true) , the other members can view my camera video;
> 
> but my local VideoTrackRenderer gave a black container withoth anything;

This is actually related to not setting state to update UI after videotrack muted.

https://github.com/livekit/client-sdk-flutter/commit/82e8a9eedfc3b59932338a5ba93f6cf5934bca0c#diff-7e0e2f20d71da6c7c83c6cc42b2fc91534b17a40cfcd849b12f7e306e470648cR132

**Comment by lxl518000** [comment]
> 嘿@lxl518000, 录制视频时使用的示例是什么版本？ 请尝试应用此补丁[82e8a9e](https://github.com/livekit/client-sdk-flutter/commit/82e8a9eedfc3b59932338a5ba93f6cf5934bca0c) 我似乎无法在测试中重现此问题。

hi there, i just record a new video today via  compile the latest example code;
see this 


https://user-images.githubusercontent.com/7520801/191973660-89efab64-7025-43c9-b514-8868e1e72425.mp4

first disable the camera.  and then enable it ,
you might got a exception like  android decode... failed. and you got a black container.
 after that, the camera will not released after exit room.

toggle sometimes ,sometimes we can got track again.

**Comment by cloudwebrtc** [comment]
okay, can you paste the exception message you got? UI invalidation may be related to this exception thrown, which prevents the normal update of UI state.

**Comment by lxl518000** [comment]
> okay, can you paste the exception message you got? UI invalidation may be related to this exception thrown, which prevents the normal update of UI state.
> 
> especially errorCode and errorMessage


I/org.webrtc.Logging( 4122): CameraStatistics: Camera fps: 29.
I/org.webrtc.Logging( 4122): EglRenderer: Duration: 4007 ms. Frames received: 97. Dropped: 1. Rendered: 96. Render fps: 24.0. Average render time: 2385 us. Average swapBuffer time: 1270 us.
I/org.webrtc.Logging( 4122): CameraStatistics: Camera fps: 28.
I/flutter ( 4122): 14:26:40: setSourceEnabled(source: TrackSource.camera, enabled: false)
I/flutter ( 4122): 14:26:40: LocalTrack.mute() muted: false
I/flutter ( 4122): 14:26:40: LocalVideoTrack#288872636.disable() disabling MediaStreamTrackNative#292325920...
I/flutter ( 4122): 14:26:40: LocalVideoTrack#288872636.stop()
I/flutter ( 4122): 14:26:40: Stopping mediaStreamTrack...
I/org.webrtc.Logging( 4122): CameraCapturer: Stop capture
I/org.webrtc.Logging( 4122): CameraCapturer: Stop capture: Nulling session
I/org.webrtc.Logging( 4122): CameraCapturer: Stop capture done
I/org.webrtc.Logging( 4122): Camera2Session: Stop camera2 session on camera 1
I/org.webrtc.Logging( 4122): CameraCapturer: dispose
I/org.webrtc.Logging( 4122): CameraCapturer: Stop capture
I/org.webrtc.Logging( 4122): Camera2Session: Stop internal
I/org.webrtc.Logging( 4122): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging( 4122): CameraCapturer: Stop capture: No session open
I/org.webrtc.Logging( 4122): CameraCapturer: Stop capture done
I/org.webrtc.Logging( 4122): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging( 4122): Camera2Session: Stop done
I/org.webrtc.Logging( 4122): Camera2Session: Camera device closed.
D/FlutterWebRTCPlugin( 4122): CameraEventsHandler.onFirstFrameAvailable
I/org.webrtc.Logging( 4122): SurfaceTextureHelper: dispose()
I/org.webrtc.Logging( 4122): GlShader: Deleting shader.
I/flutter ( 4122): 14:26:40: [TrackEvent] TrackMuteUpdatedEvent(track: Instance of 'LocalVideoTrack', muted: true), will notifyListeners()
I/flutter ( 4122): 14:26:40: LocalTrackPublication<LocalVideoTrack>(sid: TR_VC7tKxzDnRSRBb, source: TrackSource.camera) Sending mute signal... sid:TR_VC7tKxzDnRSRBb, muted:true
I/flutter ( 4122): 14:26:40: [ParticipantEvent] TrackMutedEvent(participant: LocalParticipant(sid: PA_B3AHsuU3bMZC, identity: 21), publication: LocalTrackPublication<LocalVideoTrack>(sid: TR_VC7tKxzDnRSRBb, source: TrackSource.camera)), will notifyListeners()
I/flutter ( 4122): 14:26:40: [RoomEvent] TrackMutedEvent(participant: LocalParticipant(sid: PA_B3AHsuU3bMZC, identity: 21), publication: LocalTrackPublication<LocalVideoTrack>(sid: TR_VC7tKxzDnRSRBb, source: TrackSource.camera)), will notifyListeners()
W/FlutterWebRTCPlugin( 4122): FlutterRTCVideoRenderer.setVideoTrack, set video track to null
I/org.webrtc.Logging( 4122): EglRenderer: Releasing.
I/org.webrtc.Logging( 4122): GlShader: Deleting shader.
I/org.webrtc.Logging( 4122): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging( 4122): EglRenderer: Quitting render thread.
I/org.webrtc.Logging( 4122): EglRenderer: Releasing done.
I/flutter ( 4122): 14:26:40: [SignalEvent] Instance of 'SignalParticipantUpdateEvent'
I/flutter ( 4122): 14:26:40: [ParticipantEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_B3AHsuU3bMZC, identity: 21), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
I/flutter ( 4122): 14:26:40: [RoomEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_B3AHsuU3bMZC, identity: 21), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
I/flutter ( 4122): 14:26:42: setSourceEnabled(source: TrackSource.camera, enabled: true)
I/flutter ( 4122): 14:26:42: LocalTrack.unmute() muted: true
I/FlutterWebRTCPlugin( 4122): getUserMedia(video): ConstraintsMap{mMap={frameRate=25, facingMode=user, width=960, height=540}}
D/FlutterWebRTCPlugin( 4122): Creating video capturer using Camera2 API.
D/FlutterWebRTCPlugin( 4122): Create front camera 1 succeeded
D/HostConnection( 4122): HostConnection::get() New Host Connection established 0xc34382c0, tid 6684
D/HostConnection( 4122): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging( 4122): EglBase14Impl: Using OpenGL ES version 2
D/eglCodecCommon( 4122): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 4122): eglCreateContext: 0xc15ae6c0: maj 3 min 0 rcv 3
D/EGL_emulation( 4122): eglMakeCurrent: 0xc15ae6c0: ver 3 0 (tinfo 0xc2fae590)
E/EGL_emulation( 4122): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation( 4122): tid 6684: eglQueryContext(1902): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/org.webrtc.Logging( 4122): CameraCapturer: startCapture: 960x540@25
I/org.webrtc.Logging( 4122): Camera2Session: Create new camera2 session on camera 1
I/org.webrtc.Logging( 4122): Camera2Session: start
D/FlutterWebRTCPlugin( 4122): changeCaptureFormat: 960x540@25
D/FlutterWebRTCPlugin( 4122): MediaStream id: 99749bfe-1537-4b4e-bcd8-ab61bb10c9cf
I/org.webrtc.Logging( 4122): Camera2Session: Available preview sizes: [1280x720, 640x480, 320x240, 176x144, 1920x1080]
I/org.webrtc.Logging( 4122): Camera2Session: Available fps ranges: [[15.0:30.0], [30.0:30.0]]
I/org.webrtc.Logging( 4122): Camera2Session: Using capture format: 640x480@[15.0:30.0]
I/org.webrtc.Logging( 4122): Camera2Session: Opening camera 1
D/FlutterWebRTCPlugin( 4122): CameraEventsHandler.onCameraOpening: cameraName=1
I/flutter ( 4122): 14:26:42: LocalVideoTrack#288872636.start()
I/flutter ( 4122): 14:26:42: [TrackEvent] Instance of 'TrackStreamUpdatedEvent', will notifyListeners()
I/flutter ( 4122): 14:26:42: LocalVideoTrack#288872636.enable() enabling MediaStreamTrackNative#75118410...
I/flutter ( 4122): 14:26:42: [TrackEvent] Instance of 'LocalTrackOptionsUpdatedEvent', will notifyListeners()
I/flutter ( 4122): 14:26:42: [TrackEvent] TrackMuteUpdatedEvent(track: Instance of 'LocalVideoTrack', muted: false), will notifyListeners()
I/flutter ( 4122): 14:26:42: LocalTrackPublication<LocalVideoTrack>(sid: TR_VC7tKxzDnRSRBb, source: TrackSource.camera) Sending mute signal... sid:TR_VC7tKxzDnRSRBb, muted:false
I/org.webrtc.Logging( 4122): Camera2Session: Camera opened.
I/org.webrtc.Logging( 4122): Camera2Session: Camera capture session configured.
I/org.webrtc.Logging( 4122): Camera2Session: Stabilization not available.
I/org.webrtc.Logging( 4122): Camera2Session: Using continuous video auto-focus.
I/flutter ( 4122): 14:26:42: [ParticipantEvent] TrackUnmutedEvent(participant: LocalParticipant(sid: PA_B3AHsuU3bMZC, identity: 21), publication: LocalTrackPublication<LocalVideoTrack>(sid: TR_VC7tKxzDnRSRBb, source: TrackSource.camera)), will notifyListeners()
I/flutter ( 4122): 14:26:42: [RoomEvent] TrackUnmutedEvent(participant: LocalParticipant(sid: PA_B3AHsuU3bMZC, identity: 21), publication: LocalTrackPublication<LocalVideoTrack>(sid: TR_VC7tKxzDnRSRBb, source: TrackSource.camera)), will notifyListeners()
I/org.webrtc.Logging( 4122): Camera2Session: Camera device successfully started.
I/org.webrtc.Logging( 4122): CameraCapturer: Create session done. Switch state: IDLE
I/org.webrtc.Logging( 4122): SurfaceTextureHelper: Setting listener to org.webrtc.Camera2Session$CaptureSessionCallback$$ExternalSyntheticLambda0@5c9279b
I/org.webrtc.Logging( 4122): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging( 4122): EglRenderer: EglBase.create shared context
D/HostConnection( 4122): HostConnection::get() New Host Connection established 0xc1617320, tid 6690
D/HostConnection( 4122): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging( 4122): EglBase14Impl: Using OpenGL ES version 2
D/eglCodecCommon( 4122): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 4122): eglCreateContext: 0xc15af2c0: maj 3 min 0 rcv 3
W/FlutterWebRTCPlugin( 4122): FlutterRTCVideoRenderer.setVideoTrack, set video track to 46486f55-2601-45c2-9f6c-1f0466d77412
I/org.webrtc.Logging( 4122): EglRenderer: Releasing.
D/EGL_emulation( 4122): eglMakeCurrent: 0xc15af2c0: ver 3 0 (tinfo 0xc327d140)
I/org.webrtc.Logging( 4122): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging( 4122): EglRenderer: Releasing done.
I/org.webrtc.Logging( 4122): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging( 4122): EglRenderer: Quitting render thread.
I/flutter ( 4122): 14:26:42: [SignalEvent] Instance of 'SignalParticipantUpdateEvent'
I/flutter ( 4122): 14:26:42: [ParticipantEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_B3AHsuU3bMZC, identity: 21), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
I/flutter ( 4122): 14:26:42: [RoomEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_B3AHsuU3bMZC, identity: 21), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
I/org.webrtc.Logging( 4122): EglRenderer: EglBase.create shared context
D/HostConnection( 4122): HostConnection::get() New Host Connection established 0xc1617320, tid 6691
D/HostConnection( 4122): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging( 4122): EglBase14Impl: Using OpenGL ES version 2
I/flutter ( 4122): 14:26:42: [SignalEvent] Instance of 'SignalSubscribedQualityUpdatedEvent'
D/eglCodecCommon( 4122): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 4122): eglCreateContext: 0xc15afa40: maj 3 min 0 rcv 3
D/EGL_emulation( 4122): eglMakeCurrent: 0xc15afa40: ver 3 0 (tinfo 0xc327d350)
I/flutter ( 4122): 14:26:42: Update publishing layers: [, quality: MEDIUM
I/flutter ( 4122): , quality: HIGH
I/flutter ( 4122): ]
I/flutter ( 4122): 14:26:42: Processing encoding: f...
I/flutter ( 4122): 14:26:42: Setting layer HIGH to false
I/flutter ( 4122): 14:26:42: Processing encoding: h...
D/FlutterWebRTCPlugin( 4122): CameraEventsHandler.onFirstFrameAvailable
I/flutter ( 4122): 14:26:42: Setting layer MEDIUM to false
I/flutter ( 4122): 14:26:42: Processing encoding: q...
I/flutter ( 4122): 14:26:42: Setting layer LOW to false
I/org.webrtc.Logging( 4122): CameraStatistics: Camera fps: 28.
I/org.webrtc.Logging( 4122): CameraStatistics: Camera fps: 28.
I/org.webrtc.Logging( 4122): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 4122): CameraStatistics: Camera fps: 29.


this time i  didn't got exception, the camera is still on ,but i got a black

**Comment by lxl518000** [comment]
> okay, can you paste the exception message you got? UI invalidation may be related to this exception thrown, which prevents the normal update of UI state.
> 
> especially errorCode and errorMessage

this time i got a exception


![image](https://user-images.githubusercontent.com/7520801/191985570-28b831f1-20f5-4527-8776-7854d2280839.png)

stConnection( 4122): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/org.webrtc.Logging( 4122): EglBase14Impl: Using OpenGL ES version 2
D/eglCodecCommon( 4122): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 4122): eglCreateContext: 0xc35fcc20: maj 3 min 0 rcv 3
D/EGL_emulation( 4122): eglMakeCurrent: 0xc35fcc20: ver 3 0 (tinfo 0xc3287690)
I/flutter ( 4122): 14:34:25: [SignalEvent] Instance of 'SignalSubscribedQualityUpdatedEvent'
I/flutter ( 4122): 14:34:25: Update publishing layers: [, quality: MEDIUM
I/flutter ( 4122): , quality: HIGH
I/flutter ( 4122): ]
I/flutter ( 4122): 14:34:25: Processing encoding: f...
I/flutter ( 4122): 14:34:25: Setting layer HIGH to false
I/flutter ( 4122): 14:34:25: Processing encoding: h...
I/flutter ( 4122): 14:34:25: Setting layer MEDIUM to false
I/flutter ( 4122): 14:34:25: Processing encoding: q...
I/flutter ( 4122): 14:34:25: Setting layer LOW to false
E/MethodChannel#FlutterWebRTC.Method( 4122): Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method( 4122): java.lang.IllegalStateException: MediaStreamTrack has been disposed.
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at org.webrtc.MediaStreamTrack.checkMediaStreamTrackExists(MediaStreamTrack.java:120)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at org.webrtc.MediaStreamTrack.id(MediaStreamTrack.java:83)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer.setVideoTrack(FlutterRTCVideoRenderer.java:175)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer.setStream(FlutterRTCVideoRenderer.java:155)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:441)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#FlutterWebRTC.Method( 4122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/FlutterWebRTCPlugin( 4122): CameraEventsHandler.onFirstFrameAvailable

**Comment by cloudwebrtc** [comment]
Aha, MediaStreamTrack seems to be disposed twice

**Comment by cloudwebrtc** [comment]
What version of this android emulator are you using? I can try to reproduce this issue locally

**Comment by lxl518000** [comment]
![image](https://user-images.githubusercontent.com/7520801/191986806-9840e9a2-f74f-4d8d-8fa6-835fb3a2873b.png)

**Comment by lxl518000** [comment]
> ![image](https://user-images.githubusercontent.com/7520801/191986806-9840e9a2-f74f-4d8d-8fa6-835fb3a2873b.png)

The same scene can also appear on my mobile phone

**Comment by cloudwebrtc** [comment]
okay, thanks.

**Comment by lxl518000** [comment]
> okay, thanks.

i am going to take care of my baby, see you later！

thank's for your contribution , have a good night~~

**Comment by cloudwebrtc** [comment]
@lxl518000 I have tested it many times and found that this problem will reproduce when the simulcast is turned on. When simulcast is turned off, the local video can be switched very well. Can you help me verify this problem?

**Comment by lxl518000** [comment]
> @lxl518000 I have tested it many times and found that this issue will reproduce when the simulcast is turned on. When the simulcast is turned off, the local video can be switched very well. Can you help me verify this issue?
> 
> And I traced the native code, when I get the VideoTrack from GetUserMeia, but when I call the `setStream` from RTCRenderer, `VideoTrack.nativeTrack` is reset to 0 causing the exception to be thrown

ye ， my pleasure.
I'll test it in a while ！

**Comment by lxl518000** [comment]
> @lxl518000 I have tested it many times and found that this issue will reproduce when the simulcast is turned on. When the simulcast is turned off, the local video can be switched very well. Can you help me verify this issue?
> 
> And I traced the native code, when I get the VideoTrack from GetUserMeia, but when I call the `setStream` from RTCRenderer, `VideoTrack.nativeTrack` is reset to 0 causing the exception to be thrown

@cloudwebrtc My test is the same as your result. 
When the simulcast is disabled, it can run well. 
Once the simulcast is enabled, a black container will appear during the first switching, and the subsequent switching can be displayed normally. In this case,  the camera will not be released if you didn't disable the camera.

so, can this problem be solved?

**Comment by cloudwebrtc** [comment]
Yes, I am trying to solve (recompile the debug version of libwebrtc.aar), this may be related to `VideoTrack` being held multiple times but not fully released.

**Comment by FreddyKaiser** [comment]
I can reproduce the problem too; and I'm able to get rid of the black screen by calling `track.setCameraPosition(...)`

**Comment by FreddyKaiser** [comment]
And it seems only to be the case on Android, same code / app on iOS is working fine

**Comment by lxl518000** [comment]
> @lxl518000 I have tested it many times and found that this issue will reproduce when the simulcast is turned on. When the simulcast is turned off, the local video can be switched very well. Can you help me verify this issue?
> 
> And I traced the native code, when I get the VideoTrack from GetUserMeia, but when I call the `setStream` from RTCRenderer, `VideoTrack.nativeTrack` is reset to 0 causing the exception to be thrown

hi there, i test that if turned off simulcast ,just toggle camera looks well. 
but if you toggle mute or unmute after toggleed camera,the same scene appered . that your videorender stack. and not released when exit.

by the way, is there any progress on this issue 。 thanks. @cloudwebrtc

**Comment by cloudwebrtc** [comment]
Yes, I have located the issue. This is related to the takeOwnership of RtpSender.setTrack in the Android SDK. I think I have fixed it. I will create an update of flutter-webrtc tomorrow and fix this issue

**Comment by cloudwebrtc** [comment]
@lxl518000 Fixed in this PR https://github.com/flutter-webrtc/flutter-webrtc/pull/1091.

**Comment by lxl518000** [comment]
> 
glad to hear this， expect for pub update!

**Comment by FreddyKaiser** [comment]
@cloudwebrtc thanks for fixining this, is there a version I could check in the meantime it will get released over pub.dev ?

**Comment by fpasalioglu** [comment]
I think the problem still exists. I am using version 0.9.8 of flutter_webrtc library. But there is a black screen problem. The sound is heard, when spoken, there is a blue stripe around the Container, but it looks black inside.

**Comment by lxl518000** [comment]
> @cloudwebrtc I think the problem still exists. I am using version 0.9.8 of flutter_webrtc library. But there is a black screen problem. The sound is heard, when spoken, there is a blue stripe around the Container, but it looks black inside.

i think this version has fixed my question before.
I  can switch the camera normally.

**Comment by FreddyKaiser** [comment]
> @cloudwebrtc thanks for fixining this, is there a version I could check in the meantime it will get released over pub.dev ?
I can confirm it has been fixed, at least for me, with `livekit_client: 1.1.5`
